name: prob-specs
channels:
  - pytorch
dependencies:
  - python=3.10
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.3
  - numpy=1.25.*
  - scipy=1.11.*
  - packaging=20.*
  - pytest=7.4.*
  - pylint=2.16.*
  - appdirs=1.4.*
  - pyyaml=6.*
  - ninja=1.10.*
  - tqdm=4.65.*
  - seaborn=0.12.2
  - pandas=2.1.4
  - pip
  - pip:
    - pytest-order>=1.1.0,<1.2.0
    - frozendict>=2.3.8,<3.0
    - rust_enum==1.1.5
    - adult-dataset>=3.0.0,<4.0
    - multiprocess==0.70.15
    - scikit-learn>=1.3.2,<1.4.0
    - kmodes==0.12.2
    - optuna>=3.5.0,<4.0
    - matplotlib>=3.8.2,<3.9.0
    - randomname==0.2.1
    - ruamel.yaml==0.18.6
    - jupyter
